import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult, DetectionVerdict } from "../types";

const SYSTEM_INSTRUCTION = `
You are an expert digital forensics analyst specializing in AI-generated imagery, specifically focusing on models developed by Google (such as Imagen 2, Imagen 3, Gemini, and Veo).

Your task is to analyze the provided image and determine if it was likely generated by a Google AI model. 

Analyze for:
1. Specific artifacts common to diffusion or transformer-based image models (e.g., text rendering issues, symmetry errors, unnatural textures, "plastic" skin smoothing).
2. Stylistic markers often associated with Google's safety filters and aesthetic preferences (e.g., high saturation, specific lighting styles).
3. Compositional patterns.

Return the result in a strict JSON format.
- verdict: "Yes", "No", or "Not sure".
- confidence: A number between 0 and 100 representing your certainty.
- reasoning: A concise explanation (max 2 sentences) of why you made this determination.
`;

export const analyzeImageWithGemini = async (base64Image: string, mimeType: string): Promise<AnalysisResult> => {
  try {
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      throw new Error("API Key is missing");
    }

    const ai = new GoogleGenAI({ apiKey });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Image
            }
          },
          {
            text: "Analyze this image. Was it created by a Google AI model?"
          }
        ]
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            verdict: {
              type: Type.STRING,
              enum: [DetectionVerdict.YES, DetectionVerdict.NO, DetectionVerdict.NOT_SURE],
              description: "Whether the image is likely created by Google AI."
            },
            confidence: {
              type: Type.NUMBER,
              description: "Confidence score from 0 to 100."
            },
            reasoning: {
              type: Type.STRING,
              description: "Brief reasoning for the verdict."
            }
          },
          required: ["verdict", "confidence", "reasoning"]
        }
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response text received from Gemini");
    }

    const result = JSON.parse(text) as AnalysisResult;
    return result;

  } catch (error) {
    console.error("Error analyzing image:", error);
    throw error;
  }
};
